sudo: required

env:
  global:
    - DOCKER_VERSION=1.9.1  # Install Docker version 1.9.1

services:
  - docker

script:
  - docker build -t zokeber/mongodb:latest .
  - docker run -d -p 27017:27017 --name mongodb zokeber/mongodb
  - docker ps -a
