sudo: true

env:
  global:
    - DOCKER_VERSION=1.9.1  # Install Docker version 1.9.1

services:
  - docker

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run "docker build -t zokeber/mongodb ."
